name: "Coq latest"

on:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catalalang/catala-coq-ci  

    steps:
      - name: dirty hack
        run: |
          mkdir -p /lib/coq/user-contrib/
          mkdir -p /lib/coq/8.20/user-contrib/Autosubst
          ln -s /lib/coq/8.20/user-contrib/Autosubst /lib/coq/user-contrib/
        
      - name: Check Coq installation
        run: |
          coqc --version
          coqc --where

      - name: Checkout tree
        uses: actions/checkout@v1

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest