name: "CI"
on:
  pull_request:
  push:
    branches:
      main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix develop
    - run: nix build
    - run: nix build .#catala_8_13
