name: "Coq latest"

on:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catalalang/catala-coq-ci  

    steps:
      - name: Check Coq installation
        run: coqc --version

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest
